version: "3.8"

services:
  app:
    build: .
    container_name: go-microservice
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=mypswd
      - DB_NAME=app_db
      - DB_PORT=5435
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config:/app/config # ТОЛЬКО конфиги, а не весь код!

  postgres:
    image: postgres:15
    container_name: go-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypswd
      POSTGRES_DB: app_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
