version: "3.8"

services:
  app:
    build: .
    container_name: go-microservice
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - ./config:/app/config
    env_file:
      - .env.local

  postgres:
    image: postgres:15
    container_name: go-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypswd
      POSTGRES_DB: app_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: go-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
